fail_fast: true
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
            -   id: trailing-whitespace
                language: python
            -   id: forbid-new-submodules
            -   id: check-case-conflict
            -   id: check-yaml
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: debug-statements
            -   id: no-commit-to-branch

    -   repo: https://github.com/ambv/black
        rev: 20.8b1
        hooks:
            -   id: black
                language_version: python3.8
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.9.0
        hooks:
            -   id: flake8
    -   repo: https://github.com/asottile/blacken-docs
        rev: v1.10.0
        hooks:
            -   id: blacken-docs
